//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyProduct("Concise.Steps")]
[assembly: AssemblyVersion("0.3.1.0")]
[assembly: AssemblyFileVersion("0.3.1.0")]
[assembly: AssemblyInformationalVersion("0.3.1+1.Branch.master.Sha.f41827a0428847d6501d6b3bce9dc5e5f55a4193")]
[assembly: AssemblyCopyright("Copyright Todd Lindsey 2017")]

