//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyProduct("Concise.Steps")]
[assembly: AssemblyVersion("0.3.1.0")]
[assembly: AssemblyFileVersion("0.3.1.0")]
[assembly: AssemblyInformationalVersion("0.3.1+2.Branch.master.Sha.4e55792c72bbe21fffb71b14d2b035e1a926c89d")]
[assembly: AssemblyCopyright("Copyright Todd Lindsey 2017")]

